# Dependencies
markdown:         kramdown
# markdown :        rdiscount
pygments:         true

# Permalinks
permalink:        pretty

# Setup
title:            Python code made in Bavaria
tagline:          'Potzenheimer'
description:      'A brazen two-column <a href="http://jekyllrb.com" target="_blank">Jekyll</a> theme that pairs a prominent sidebar with uncomplicated content. Made by <a href="https://twitter.com/mdo" target="_blank">@mdo</a>.'
url:              http://hyde.getpoole.com

author:
  name:           'Christoph Böhner'
  url:            https://twitter.com/potzenheimer

paginate:         5

# Custom vars
version:          2.0.0

github:
  repo:           https://github.com/potzenheimer

# Server
destination:      ./_site
exclude:          [".editorconfig", ".gitignore", ".bowerrc", "jshintrc", "bower.json", "config.json", "Gruntfile.js", "package.json", "manifest.cfg", "rules.xml", "node_modules", "bower_components", "README.md", "assets", "less", "dist", "js", "overrides", "docs", "templates", "Makefile"]
port:             9001
